require('settings')
require('colorschemes-config.dracula')
require('packer-config')
require('nvim-tree-config')
require('mappings')
require('lsp-config.lsp')
require('lsp-config.null-ls')
require('lsp-config.completion')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('neoscroll-config')
require('gitsigns-config')
require('shade-config')
require('mason-config')
-- require('surround-config')
require('autopairs-config')
require('toggleterm-config')
